version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./server/.env
    depends_on:
      - redis

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - server

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"